CREATE TABLE EMPLOYEE
( Fname VARCHAR(15) NOT NULL,
 Minit CHAR,
 Lname VARCHAR(15) NOT NULL,
 Ssn CHAR(9) NOT NULL,
 BDate DATE,
 Address VARCHAR(30),
 Sex CHAR,
 Salary DECIMAL(10,2),
 Super_ssn CHAR(9),
 Dno INT NOT NULL,
 PRIMARY KEY (Ssn) );

 CREATE TABLE DEPARTMENT
 ( Dname VARCHAR(15) NOT NULL,
 Dnumber INT NOT NULL,
 Mgr_ssn CHAR(9) NOT NULL,
 Mgr_start_date DATE,
 PRIMARY KEY (Dnumber),
 UNIQUE (Dname) );

 CREATE TABLE DEPT_LOCATIONS
 ( Dnumber INT NOT NULL,
 Dlocation VARCHAR(15) NOT NULL,
 PRIMARY KEY (Dnumber, Dlocation) );

 CREATE TABLE PROJECT
 (Pname VARCHAR(15) NOT NULL,
 Pnumber INT NOT NULL,
 Plocation VARCHAR(15),
 Dnum INT NOT NULL,
 PRIMARY KEY (Pnumber),
 UNIQUE (PName) );

 CREATE TABLE WORKS_ON
 (Essn CHAR(9) NOT NULL,
 Pno INT NOT NULL,
 Hours DECIMAL(3, 1) NOT NULL,
 PRIMARY KEY (Essn, Pno) );

 CREATE TABLE DEPENDENT
 ( Essn CHAR(9) NOT NULL,
 Dependent_name VARCHAR(15) NOT NULL,
 SEX CHAR,
 Bdate DATE,
 Relationship VARCHAR(8),
 PRIMARY KEY (Essn, Dependent_name) );
 

 /* Manually created data within tables before adding constraints */

ALTER TABLE EMPLOYEE ADD FOREIGN KEY (Dno) REFERENCES DEPARTMENT(Dnumber);
ALTER TABLE EMPLOYEE ADD FOREIGN KEY (Super_ssn) REFERENCES EMPLOYEE(Ssn);
ALTER TABLE DEPARTMENT ADD FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE(Ssn);
ALTER TABLE DEPT_LOCATIONS ADD FOREIGN KEY (Dnumber) REFERENCES DEPARTMENT(Dnumber);
ALTER TABLE PROJECT ADD FOREIGN KEY (Dnum) REFERENCES DEPARTMENT(Dnumber);
ALTER TABLE WORKS_ON ADD FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn);
ALTER TABLE WORKS_ON ADD FOREIGN KEY (Pno) REFERENCES PROJECT(Pnumber);
ALTER TABLE DEPENDENT ADD FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn);

